services:
  web-recon-tools:
    container_name: web-recon-tools
    image: tco/web-recon-tools:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./wordlists:/root/wordlists
    ports:
      - '9999:9999'
      - '22222:22'
